// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateObjectReducer from "../create_object_reducer";
import DeleteObjectReducer from "../delete_object_reducer";
import IncrementTalkCountReducer from "../increment_talk_count_reducer";
import UpdateObjectReducer from "../update_object_reducer";

export type CreateObjectParams = __Infer<typeof CreateObjectReducer>;
export type DeleteObjectParams = __Infer<typeof DeleteObjectReducer>;
export type IncrementTalkCountParams = __Infer<typeof IncrementTalkCountReducer>;
export type UpdateObjectParams = __Infer<typeof UpdateObjectReducer>;

