// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  personality: __t.string(),
  backstory: __t.string(),
  voiceDescription: __t.string().name("voice_description"),
  imageUrl: __t.string().name("image_url"),
  originalImageUrl: __t.string().name("original_image_url"),
  voiceId: __t.string().name("voice_id"),
  voiceName: __t.string().name("voice_name"),
  timesTalkedTo: __t.u32().name("times_talked_to"),
  createdAt: __t.timestamp().name("created_at"),
});
