// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const NpcObject = __t.object("NpcObject", {
  id: __t.string(),
  name: __t.string(),
  personality: __t.string(),
  backstory: __t.string(),
  voiceDescription: __t.string(),
  imageUrl: __t.string(),
  originalImageUrl: __t.string(),
  voiceId: __t.string(),
  voiceName: __t.string(),
  mode: __t.string(),
  timesTalkedTo: __t.u32(),
  createdAt: __t.timestamp(),
});
export type NpcObject = __Infer<typeof NpcObject>;

